(autoload 'map-with-progress-reporter           "map-progress" "" nil 'macro)
(autoload 'mapc-with-progress-reporter          "map-progress" "" nil 'macro)
(autoload 'mapcan-with-progress-reporter        "map-progress" "" nil 'macro)
(autoload 'mapcar-with-progress-reporter        "map-progress" "" nil 'macro)
(autoload 'mapcon-with-progress-reporter        "map-progress" "" nil 'macro)
(autoload 'mapl-with-progress-reporter          "map-progress" "" nil 'macro)
(autoload 'maplist-with-progress-reporter       "map-progress" "" nil 'macro)
(autoload 'mapatoms-with-progress-reporter      "map-progress" "" nil 'macro)
(autoload 'maphash-with-progress-reporter       "map-progress" "" nil 'macro)
(autoload 'map-keymap-internal-with-progress-reporter "map-progress" "" nil 'macro)
(autoload 'with-message                         "map-progress" "" nil 'macro)
(provide 'lib-map-progress-epackage-autoloads)
